name: "Temp PR Workflow"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Get Pull Request Number
        run: |
          echo "$(git log -1 --pretty=%B | cat | grep -oe '\d*')"
          echo "Testing" 
          echo "End Testing" 
